#####################################################################
# +---------------------------------------------------------------+ #
# |                       Basic Settings                          | #
# +---------------------------------------------------------------+ #
#####################################################################

# Language and basic configurations
language: "en" # Supported languages -> de, en
set-bounty-on-death: false # If someone kills the bounty, the killer becomes the bounty.

database:
  type: "h2" # Supported database types -> h2, mysql
  mysql:
    host: "localhost"
    port: 3306
    database: "user"
    username: "root"
    password: ""
    # Advanced MySQL settings (modify only if you know what you're doing)
    ssl: false
    certificateverification: false
    poolsize: 10
    lifetime: 1800000

# Placeholder configuration for yes/no text in messages
placeholder:
  yes: "&aYes"
  no: "&cNo"

# Maximum allowed values
max:
  top-to-get: 15 # Maximum number of entries in the top list
  bounty-per-player: 5 # Maximum number of bounties a player can set

##########################################################################
# +--------------------------------------------------------------------+ #
# |                       Dependency Settings                          | #
# +--------------------------------------------------------------------+ #
##########################################################################

# Dependency configuration, including level and money constraints

dependency:
  level:
    enabled: true # Enable or disable level dependency
    min: 0        # Minimum level required
    max: 0        # Maximum level allowed
  money:
    min: 0        # Minimum money required
    max: 0        # Maximum money allowed

###################################################################
# +-------------------------------------------------------------+ #
# |                       Items & GUIs                          | #
# +-------------------------------------------------------------+ #
###################################################################

# Configuration for bounty-related items and the graphical interface

# Bounty item details (as shown in the GUI)
bounty-item:
  amount: 1
  material: "PAPER"
  name: "&c&l! &6{target} &8(&7{id}&8) &c&l!"
  lore:
    - ""
    - "&6Sender: &f{player} &c⚡"
    - "&6Reward: &f{reward} &c⚡"
    - "&6Reward Type: &f{reward_type} &c⚡"
    - "&6Streak: &f{streak} &c🔥"

# Bounty finder item details
bountyfinder-item:
  enabled: false
  amount: 1
  material: "COMPASS"
  name: "&e&lBOUNTYFINDER"
  lore:
    - ""
    - "&eHold this item in your hand,"
    - "&eto see which bounty is closest to you"

# Menu settings
menu:
  title: "&6&lBOUNTIES" # Menu title
  size: 54               # Menu size (number of slots)
  update-tick: 2         # How often the menu updates
  filler-glass: false    # Enable or disable filler glass

  # Back button item details
  back-item:
    amount: 1
    material: "RED_STAINED_GLASS"
    name: "&cBack"
    slot: 45

  # Forward button item details
  forward-item:
    amount: 1
    material: "GREEN_STAINED_GLASS"
    name: "&aForward"
    slot: 53

  # Filler glass item details
  filler-glass-item:
    material: GRAY_STAINED_GLASS_PANE
    name: " "   # An empty name for the filler glass
    lore: [ ]    # Empty lore for the filler glass

##########################################################################
# +--------------------------------------------------------------------+ #
# |                       Formatting Settings                          | #
# +--------------------------------------------------------------------+ #
##########################################################################

# Number formatting configuration

formatting:
  enabled: true     # Enable or disable formatting
  type: dot         # Supported types: dot, commas, basic
  basic:            # Abbreviations for large numbers
    '1000': K       # Thousand -> K
    '1000000': M    # Million -> M
    '1000000000': B # Billion -> B
    '1000000000000': T # Trillion -> T

# Formatting types:
# dot = 1.000.000
# commas = 1,000,000
# basic = 1M

###############################################################
# +---------------------------------------------------------+ #
# |                       Features                          | #
# +---------------------------------------------------------+ #
###############################################################

# Feature-specific configurations

feature:
  glowing:
    enabled: false # Enable or disable the glowing feature for bounties
    color: "RED"   # Glowing color (if enabled)

  random-bounty:
    enabled: false       # Enable or disable random bounty generation
    rewardType: "TOKEN"  # Reward type for random bounties
    reward: 50           # Reward amount for random bounties
    per-second: 7200     # Interval (in seconds) for random bounty generation
    player-value: "CONSOLE" # Owner of random bounties

  bountyfinder:
    no-bounty-nearby: "&cNo bounties nearby" # Message when no bounty is nearby
    nearest-bounty: "&a{bounty} &8| &a{distance}m" # Message for the nearest bounty

  distance-tracker:
    enabled: false
    title: "&fHunter's position"
    style: "SOLID"
    flags: []
    colors:
      25: "RED"
      50: "YELLOW"
      100: "GREEN"

######################################################################
# +---------------------------------------------------------------+ #
# |                       Command Setting                         | #
# +---------------------------------------------------------------+ #
#####################################################################

aliases:
  - "huntmaster"
  - "bounty"
  - "hm"
